.TH "UNHIDE-TCP" "8" "January 2020" "Administration commands"
.SH "NAME"
unhide-tcp \(em forensic tool to find hidden TCP/UDP ports
.SH "SYNOPSIS"
.PP
\fBunhide-tcp\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.PP
\fBunhide-tcp\fR is a forensic tool that identifies TCP/UDP ports that are listening but are not listed by /sbin/ss (or alternatively by /bin/netstat) through brute forcing of all TCP/UDP ports avail‐ able.
.PP
Note : If iproute2 is not available on the system, option -n or -s SHOULD be given on the command line
.PP
if unhide process crash you can have a rootkit in the system with some bugs
.PP
.SH "OPTIONS"
.TP
\fB-f, --show-fuser\fR 
show fuser output for hidden ports
.TP
\fB-l, --logfile \fR 
log result into unhide-tcp.log file
.TP
\fB-n, --use-netstat\fR 
use netstat instead of ss
.TP
\fB-o, --show-lsof\fR 
show lsof output for hidden ports
.TP
\fB-s, --use-quickver\fR 
use very quick version for server with lot of opened ports
.TP
\fB-v, --verbose\fR 
verbose
.TP
\fB-?, --help\fR 
Give this help list
.TP
\fB--usage\fR 
Give a short usage message
.TP
\fB-V, --version\fR 
Print program version
.PP
.SS "Exit status:"
.TP
value different from 4, 8, or 12
if no hidden port is found,
.TP
4
if one or more hidden TCP port(s) is(are) found,
.TP
8
if one or more hidden UDP port(s) is(are) found,
.TP
12
if one or more hidden TCP and UDP ports are found.
.PP
.SH "EXAMPLES"
.TP
Standard:
unhide-tcp 
.TP
Other example:
unhide-tcp --show-fuser --show-lsof --logfile
.SH "BUGS"
.PP
Report \fBunhide\fR bugs on https://github.com/YJesus/Unhide
.br
via email dreg@fr33project.org - yjesus@security-projects.com
.SH "SEE ALSO"
.PP
unhide-tcp(8), unhide-gids(8), unhide(8), unhide-posix(8)
.SH "AUTHOR"
First version manual page was written by Francois Marier francois@debian.org and Patrick Gouin. 
.br
The current version was written by David Reguera Garcia aka Dreg.
.br
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 3 or any
later version published by the Free Software Foundation.
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
